---
miniconda_prefix: /scratch/miniconda
jenkins_public_ssh_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfQrCU7MkCPHoFt6kwBnh3kZMd38WMbP4TSmaYrRjqwNAqlW9zoyHMy/eU+Gvb87hjSm9EZG8GOoHAkkqy1s7G6qQWNfYoxyQmbxs/nj3mtvFRKfow8WUmt2Xew5tXWJX1GxWtpyNn4ytrB7iGJRyiGN1R/g6qyBu/rxWtVvWxz79THajJqt5zgJFvnnLDOj9wlUIdA6lXlMOE0fUzdXsBNhZGWMwMCo+hd3i+SHsuK5QvBGPz/c9SdfzyKfg8JFmb2dfMCfybhsAeGO315qZWe1t7fgwVYiFRcOvTpZ0SR7sFPfmEAzm4sIF10n1EIADB70tfmsWsPX42oC/l4Zp1"
software_groups_to_install:
  - admin
  - editors
  - terminals
  - utils
