---
- hosts: pxe
  vars_files:
    - group_vars/pxe.yml
  pre_tasks:
    - name: system update
      ansible.builtin.dnf:
        name: "*"
        state: latest
    - name: Put SELinux in permissive mode, logging actions that would be blocked.
      ansible.posix.selinux:
        policy: targeted
        state: disabled
    - name: Alma|Rocky|CentOS | Install packages
      ansible.builtin.yum:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
  roles:
    - openslx-ng.dracut

  post_tasks:
    - name: Move dracut artifacts
      local_action: ansible.builtin.command mv "{{ playbook_dir }}/boot_files" "{{ playbook_dir | basename }}/boot_files"
